Remove failing spec
1) With ImageMagick MiniMagick::Image#details when verbose information includes a clipping path does not hang when parsing verbose data
   Failure/Error: details_hash[last_key] << line

   NoMethodError:
     undefined method `<<' for {"8BIM:1999,2998:#1"=>"<?xml version=\"1.0\" encoding=\"iso-8859-1\"?>"}:Hash

                   details_hash[last_key] << line
                                          ^^
     Did you mean?  <
   # ./lib/mini_magick/image/info.rb:149:in `block in details'
   # ./lib/mini_magick/image/info.rb:138:in `each'
   # ./lib/mini_magick/image/info.rb:138:in `each_with_object'
   # ./lib/mini_magick/image/info.rb:138:in `details'
   # ./lib/mini_magick/image/info.rb:31:in `[]'
   # ./lib/mini_magick/image.rb:145:in `block in attribute'
   # ./spec/lib/mini_magick/image_spec.rb:508:in `block (7 levels) in <top (required)>'
   # ./spec/lib/mini_magick/image_spec.rb:507:in `block (6 levels) in <top (required)>'
   # ./spec/spec_helper.rb:19:in `block (3 levels) in <top (required)>'